name: Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 7.2, 7.3, 7.4 ]
        include:
          - php: 7.2
            upload-scrutinizer: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install --no-interaction --prefer-source

      - name: Execute tests
        run: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

      - name: Upload to scrutinizer
        if: ${{ matrix.upload-scrutinizer }}
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
