name: Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 7.3, 7.4 ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install --no-interaction --prefer-source

      - name: Check code style
        run: ./vendor/bin/php-cs-fixer fix -v --dry-run

      - name: Execute tests
        run: ./vendor/bin/phpunit
